### ISSUE TITLE
Mod downloading

### ISSUE THREAD

**Issue by azukaar** [NobodyMiner/minecraft-client#2]
With the code :
```
  mods = [
    new CurseForgeMod("Iron Chests", 228756, 2595146),
  ];
  console.log(mods)
  client.checkMods(mods);
```

I get an error :  

```
[ CurseForgeMod {
    name: 'Iron Chests',
    sha1: undefined,
    type: 'CurseForge',
    url:
     'https://minecraft.curseforge.com/projects/228756/files/2595146/download' } ]

(node:16972) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at MinecraftClient.checkMods (C:\Users\azuka\Documents\dev\yanncraft\node_modules\minecraft-client\dist\app.js:76:76)
    at client.checkInstallation.then (C:\Users\azuka\Documents\dev\yanncraft\client\mc.js:21:21)
(node:16972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by xcf-t** [comment]
Can you try to reproduce this error in the latest version? I hopefully fixed this in the latest version.

**Comment by azukaar** [comment]
No change in 2.4.1
2.5.1 have the issue reported on the other ticket

**Comment by azukaar** [comment]
the error doesn't appear in 2.5.2 anymore you can close the issue
